### PR TITLE
OPSWAT Filescan Sandbox Integration

### PR DESCRIPTION
**Pull request by anikobartos**
### OPSWAT Filescan Sandbox

- Removed old opswat.py file and created a new one
- OPSWAT integration now use the OPSWAT Filescan Sandbox 
- Added test files and test cases as well
- Extended the README.rst file

For usage it is necessary to have an OPSWAT Filescan Sandbox API-key, 
Default host is [OPSWAT Filescan Community](https://www.filescan.io) 

Example availability check under sandboxapi dir (call main directly):
```
python opswat.py "https://www.filescan.io" "your-api-key" available   
```

Usage within code:
```
from sandboxapi import opswat

# connect to the sandbox
sandbox = opswat.OPSWATSandboxAPI("your-api-key")

print("Does sandbox available?")
print(sandbox.is_available())
```

### CODE REVIEW

**Comment by petya2164** [comment]
@azazelm3dj3d Do you have any feedback for us about this PR?

**Comment by azazelm3dj3d** [comment]
Hi, @petya2164.

So far, the PR is looking good. If no issues pop up, I plan to have this merged in by early next week at the latest. Thank you for the all the hard work!

**Review by azazelm3dj3d — APPROVED** [review]

**Comment by azazelm3dj3d** [comment]
I was able to finish looking at this a little earlier than anticipated. Everything looks great!

**Comment by petya2164** [comment]
@azazelm3dj3d Thank you very much for the quick review!

**Pull request merged**
